apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc
spec:
  storageClassName: azuredisk-ssd-lrs
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-blob
      volumeMounts:
        - name: files
          mountPath: "/mnt/data"
          readOnly: false
  volumes:
    - name: files
      persistentVolumeClaim:
        claimName: testpvc
