# restore-prometheus-pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restore-prometheus-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-ssd-lrs
  azureDisk:
    diskName: "prometheus-disk"
    diskURI: ""
    kind: Managed
    cachingMode: None