# pvc-63378926-bf51-4c91-bc5a-8672450ef37b
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restore-alertmanager-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-ssd-lrs
  azureDisk:
    diskName: "alertmanager-disk"
    diskURI: "/subscriptions/e07c7243-0a87-43a1-b71e-7821108e90e7/resourceGroups/MC_RG-DEV_DEV-AKS-CLUSTER-001_KOREACENTRAL/providers/Microsoft.Compute/disks/alertmanager-disk"
    kind: Managed
    cachingMode: None