# restore-prometheus-pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restore-prometheus-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-ssd-lrs
  azureDisk:
    diskName: "prometheus-disk"
    diskURI: "/subscriptions/e07c7243-0a87-43a1-b71e-7821108e90e7/resourceGroups/MC_RG-DEV_DEV-AKS-CLUSTER-001_KOREACENTRAL/providers/Microsoft.Compute/disks/prometheus-disk"
    kind: Managed
    cachingMode: None