apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyukjun-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: hyukjun-azurefile
  resources:
    requests:
      storage: 5Gi
