apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv
spec:
  storageClassName: azurefile-csi
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    volumeHandle: "RGNAME#STORAGENAME#FILESHARENAME"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: FILESHARENAME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc
spec:
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: testpv
---
kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-blob
      volumeMounts:
        - name: files
          mountPath: "/mnt/test"
          readOnly: false
  volumes:
    - name: files
      persistentVolumeClaim:
        claimName: testpvc